/** Canonical analytics event names. Keep in sync with docs/06. */
export const EVENTS = [
  "page_view",
  "tool_viewed",
  "tool_started",
  "file_uploaded",
  "upload_failed",
  "processing_started",
  "processing_completed",
  "processing_failed",
  "result_downloaded",
  "result_saved",
  "tool_shared",
  "limit_reached",
  "upgrade_viewed",
  "signup_started",
  "signup_completed",
  "login_completed",
  "password_reset_requested",
  "checkout_started",
  "checkout_completed",
  "payment_failed",
  "subscription_created",
  "subscription_cancelled",
  "credits_purchased",
  "feedback_sent",
  "error_seen",
  "admin_action",
  "health_check_failed",
  "webhook_failed",
  "api_failed",
] as const;

export type AnalyticsEvent = (typeof EVENTS)[number];
