import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Img,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import * as React from "react";

import { baseStyles, palette } from "./_styles";

export interface ConfirmAccountProps {
  /** Full confirmation URL generated by Supabase Auth */
  url: string;
  /** User's display name or email (used for personalisation) */
  name?: string;
}

export function ConfirmAccount({ url, name }: ConfirmAccountProps) {
  const greeting = name ? `Olá, ${name}!` : "Olá!";

  return (
    <Html lang="pt-BR">
      <Head />
      <Preview>Confirme seu e-mail e comece a usar o Praticca</Preview>
      <Body style={baseStyles.body}>
        <Container style={baseStyles.container}>
          <Section style={baseStyles.logoSection}>
            <Text style={baseStyles.logo}>Praticca</Text>
          </Section>

          <Section style={baseStyles.card}>
            <Heading style={baseStyles.h1}>Confirme seu e-mail</Heading>

            <Text style={baseStyles.text}>{greeting}</Text>
            <Text style={baseStyles.text}>
              Obrigado por criar sua conta no <strong>Praticca</strong>. Clique no botão abaixo
              para confirmar seu endereço de e-mail e ativar sua conta.
            </Text>

            <Section style={baseStyles.ctaSection}>
              <Button href={url} style={baseStyles.button}>
                Confirmar e-mail
              </Button>
            </Section>

            <Text style={baseStyles.hint}>
              Se você não criou uma conta no Praticca, ignore este e-mail — nenhuma ação é
              necessária.
            </Text>

            <Hr style={baseStyles.hr} />

            <Text style={baseStyles.linkFallback}>
              O botão não funciona? Copie e cole este link no navegador:
            </Text>
            <Text style={baseStyles.linkText}>{url}</Text>
          </Section>

          <Section style={baseStyles.footer}>
            <Text style={baseStyles.footerText}>
              © {new Date().getFullYear()} Praticca · Todos os direitos reservados
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

ConfirmAccount.defaultProps = {
  url: "https://praticca.com.br/auth/confirm?token=example",
  name: "Usuário",
};

export default ConfirmAccount;
