import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";
import * as React from "react";

import { baseStyles } from "./_styles";

export interface ResetPasswordProps {
  /** Password-reset URL generated by Supabase Auth */
  url: string;
  /** User's display name or email */
  name?: string;
}

export function ResetPassword({ url, name }: ResetPasswordProps) {
  const greeting = name ? `Olá, ${name}!` : "Olá!";

  return (
    <Html lang="pt-BR">
      <Head />
      <Preview>Redefinição de senha do Praticca</Preview>
      <Body style={baseStyles.body}>
        <Container style={baseStyles.container}>
          <Section style={baseStyles.logoSection}>
            <Text style={baseStyles.logo}>Praticca</Text>
          </Section>

          <Section style={baseStyles.card}>
            <Heading style={baseStyles.h1}>Redefinir senha</Heading>

            <Text style={baseStyles.text}>{greeting}</Text>
            <Text style={baseStyles.text}>
              Recebemos uma solicitação para redefinir a senha da sua conta no{" "}
              <strong>Praticca</strong>. Clique no botão abaixo para criar uma nova senha.
            </Text>

            <Text style={baseStyles.warningText}>
              Este link é válido por <strong>1 hora</strong>. Após esse prazo, você precisará
              solicitar um novo link.
            </Text>

            <Section style={baseStyles.ctaSection}>
              <Button href={url} style={baseStyles.button}>
                Redefinir senha
              </Button>
            </Section>

            <Text style={baseStyles.hint}>
              Se você não solicitou a redefinição de senha, ignore este e-mail. Sua senha
              permanece a mesma.
            </Text>

            <Hr style={baseStyles.hr} />

            <Text style={baseStyles.linkFallback}>
              O botão não funciona? Copie e cole este link no navegador:
            </Text>
            <Text style={baseStyles.linkText}>{url}</Text>
          </Section>

          <Section style={baseStyles.footer}>
            <Text style={baseStyles.footerText}>
              © {new Date().getFullYear()} Praticca · Todos os direitos reservados
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

ResetPassword.defaultProps = {
  url: "https://praticca.com.br/auth/reset-password?token=example",
  name: "Usuário",
};

export default ResetPassword;
